# Generated by Django 4.1 on 2022-08-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_frameworks_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworks',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relations.language'),
        ),
    ]
