# Generated by Django 4.1 on 2022-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_register_date_product_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SP', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GRD', 'Graduate')], default='FR', max_length=3),
        ),
    ]
